version: "3"
services:
    prod:
      build: 
          context: .
          dockerfile: Dockerfile
      ports:
          - "5200:5200"
      volumes:
            - /var/app/node_modules
            - .:/var/app


        
