version: "3"
services:
    prod:
      container_name: cpet
      build: 
          context: .
          dockerfile: Dockerfile
      ports:
          - "80:80"
      volumes:
            - /var/app/node_modules
            - .:/var/app



        
