name: 'CICD FOR CPET'

on:
  push:
    branches: [ "master" ]

jobs: 
  build:
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: use nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: build site
        run: |
          docker build -t cpet .
        env: 
          CI: true

  deploy:
    timeout-minutes: 10
    needs: [build]
    runs-on: ubuntu-latest

    steps: 
      - name: connect to SSH
        uses: appleboy/ssh-action@master
        with:
            host: ${{secrets.HOST}}     
            username: ${{secrets.USER}}  
            PORT: ${{secrets.PORT}}  
            KEY: ${{secrets.KEY}}     
            script: |
                whoami
                cd  ./cpet-test
                git pull origin master
                sudo docker stop cpet
                sudo docker container ls
                sudo docker rm -f cpet
                sudo docker-compose -f "docker-compose.yml" up -d --build
      - name: Send some mail
        uses: wadeww/send-email-action@master
        with:
          server_address: smtp.gmail.com
          port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Workflow finished
          body: Job completed ${{job.status}}
          to: muhammedfayiscc@gmail.com
          from: Me
      - name: exit
        run: |
          echo 'deployment completed.' 
